version: '3.4'

services:
  todo.api:
    image: ${DOCKER_REGISTRY-}todo-api
    build:
      context: .
      dockerfile: src/ToDo.Api/Dockerfile
    ports:
      - 5001:443

  todo.client:
    image: ${DOCKER_REGISTRY-}todo-client
    build:
      context: .
      dockerfile: src/ToDo.Client/Dockerfile
    ports:
      - 6001:443
      - 6002:80


  todo-mq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: "rabbit_node_1"
    ports:
      - 5672:5672
      - 15672:15672 
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  todo-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: todo-db
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password01!"
      ACCEPT_EULA: "Y"

volumes:
  rabbitmq:
